### ISSUE TITLE
Unable to create sqs queues automatically

### ISSUE THREAD

**Issue by MarkoR** [ahofman/NServiceBus.AmazonSQS#51]
NServiceBus.AmazonSQS version: 1.2.0
NServiceBus.Host version: 6.0.0
 
When I start service I get the following message: 
_ERROR NServiceBus.Transports.SQS.SqsDequeueStrategy Exception thrown from GetQueueUrl.
Amazon.SQS.Model.QueueDoesNotExistException: The specified queue does not exist for this wsdl version. ---> Amazon.Runtime.Internal.HttpErrorResponseException: The remote server returned an error: (400) Bad Request. ---> System.Net.WebException: The remote server returned an error: (400) Bad Request.
   at System.Net.HttpWebRequest.GetResponse()_

I double-checked that the queue was accessed from the same region it was created (in this case eu-west-1) so I believe that the error message is misleading.

**Comment by ahofman** [comment]
Thanks for reporting this @MarkoR , and apologies for not addressing this sooner. Is this issue still happening for you? Have you been able to work around the problem, if so, how? Thanks :)

**Comment by ahofman** [comment]
Haven't heard back, haven't been able to repro. Closing this issue. Feel free to re-open if you are able to repro agian.
