### ISSUE TITLE
Specify proxy in connection string?

### ISSUE THREAD

**Issue by marko-baric-travcorp** [ahofman/NServiceBus.AmazonSQS#52]
I have to access SQS through proxy server, but as far as I can see there is no way to specify proxy address and port in the connection string. Even though SQS SDK supports proxies (http://docs.aws.amazon.com/sdkfornet/latest/apidocs/). 

Am I missing something?

**Comment by ahofman** [comment]
Thanks, you're not missing anything, there's no way to specify proxy credentials at the moment. I'll add support for this shortly, probably after upgrading the AWS SDK to v3 (#53).

**Comment by ahofman** [comment]
Have merged in support for proxy authentication and updated the wiki pages accordingly. There are now two new configuration options, ProxyHost and ProxyPort. The username and password for the proxy are sourced from environment variables (I prefer to keep credentials out of connection strings where possible, to prevent them from being added to source control). 

I've tested this on my environment using Fiddler as the proxy, seems to work fine for me. These changes will be included in the 1.3 release for NSB 5, hopefully in the next week or so.

**Comment by marko-baric-travcorp** [comment]
Many thanks @ahofman
