### ISSUE TITLE
Update to NSB 6

### ISSUE THREAD

**Issue by ahofman** [ahofman/NServiceBus.AmazonSQS#57]
- [x] Port to NSB6
- [x] Get Acceptance Tests Passing
- [x] Add TransportTests and get them passing
- [x] Change MaxDop to message processing rather than concurrent tasks

**Comment by chrissimon-au** [comment]
Hi @ahofman, I'd be happy to contribute to this update - are there any tasks it would be feasible for me to assist with?

**Comment by ahofman** [comment]
Awesome, thanks @chrissimon-au  =) I'm currently working on getting all the acceptance tests passing - there are about 30 or so that still need to be fixed. Perhaps I could publish the list of tests that still fail, you could then pick up some failing tests and have a go at fixing them?

**Comment by ahofman** [comment]
Good news, all the Acceptance Tests are now passing! I've added NSB Transport Tests, and these tests all pass as well. Expect a 2.0.0 release very soon.

**Comment by ahofman** [comment]
Hi @chrissimon-au - I'd like to get in touch and have a quick chat sometime about the SQS transport (sorry, I'm not sure how else to reach you!) Perhaps we can Skype at your convenience?
