### ISSUE TITLE
Detect clock skew between endpoint and AWS

### ISSUE THREAD

**Issue by ahofman** [ahofman/NServiceBus.AmazonSQS#65]
This affects TTBR. Certain Acceptance Tests fail when the TTBR is set to 3 seconds because the clock skew is greater than this. 
Need to detect the clock skew as returned from the [AWS SDK]( https://aws.amazon.com/blogs/developer/clock-skew-correction/) and factor this in when comparing the SentTimestamp in SqsMessagePump.

**Comment by SeanFeldman** [comment]
Are you referring to this https://aws.amazon.com/blogs/developer/clock-skew-correction/?

**Comment by ahofman** [comment]
Thanks @SeanFeldman , I wasn't aware of that feature of the SDK - should be possible to use the clock skew from the SDK to adjust the SentTimestamp in SqsMessagePump.
