### ISSUE TITLE
add an icon

### ISSUE THREAD

**Issue by SimonCropp** [ahofman/NServiceBus.AmazonSQS#76]
may i suggest https://thenounproject.com/search/?q=amazon&i=962373

**Comment by ahofman** [comment]
I'm quite partial to https://thenounproject.com/search/?q=amazon&i=248859 - but to be honest there's something about the toucan that is somewhat more relatable :)

**Comment by SimonCropp** [comment]
Want a PR for it?

**Comment by ahofman** [comment]
Certainly! I'll include in the 2.0.1 release. Cheers!

**Comment by ahofman** [comment]
Unfortunately the toucan didn't looks so great when scaled down to 64x64 - went with something a bit simpler along the same lines here: #78
